# fly.toml app configuration file generated for daxx on 2023-05-19T10:39:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "daxx"
primary_region = "atl"

[http_service]
  internal_port = 8494
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
